### PR TITLE
update now() with timezone alias #271

### PR DESCRIPTION
**Pull request by levo-777**
Please add me to the contributors list Name: Mebonia Levan, username: levo-777

	modified:   sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
	modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/artifact.py
	modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/event.py
	modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/peh.py
	modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/utils.py
	modified:   sdlf-foundations/lambda/catalog/src/lambda_function.py
	modified:   sdlf-foundations/lambda/replicate/src/lambda_function.py

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by levo-777** [comment]
?

**Comment by cnfait** [comment]
Hey, thank you for the contribution! I've taken the liberty to update the PR title - your change looks good but it's also important to be clear in your PR to help potential reviewers 👍 

As for crediting you, of course you'll be listed in the [next release](https://github.com/awslabs/aws-serverless-data-lake-framework/releases), which I'm hoping to publish before the end of the month (or early March).

**Comment by levo-777** [comment]
can you add me to the contributors list pls , for this contribution ... ?

**Comment by cnfait** [comment]
https://github.com/awslabs/aws-serverless-data-lake-framework/releases/tag/2.2.0

**Pull request merged**
