### PR TITLE
Update key and bucket retention policies

### PR DESCRIPTION
**Pull request by xavierclements**
*Issue #, if available:* None

*Description of changes:*

Adding update and replace as well as deletion policies to KMS keys and buckets

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaidisido** [comment]
I agree about adding the retention policy to KMS keys but not for S3 buckets for two reasons:
1. When following the SDLF workshop, users sometimes face an issue and have to delete the entire foundations stacks. By adding a `Retain` policy on S3 buckets, reattempting to deploy the stacks will fail because the buckets are already there
2. CloudFormation cannot delete a bucket if it has data, effectively enforcing an implicit `Retain` policy by default

**Comment by xavierclements** [comment]
@jaidisido My usual policy on this is buckets are kept no matter what and that it is a conscious choice for people to clean them up before a fresh deployment. Documentation could be added to advise users that buckets would need to be deleted before a repeated deployment?

**Comment by jaidisido** [comment]
I wish people read the docs haha We had the same issue with DynamoDB tables (using `Retain`) and despite mentioning it in the docs people raised issues in GitHub about their stacks failing because resources already exist.

But as I mentioned, CloudFormation would not delete a bucket with data anyways, so what is the benefit of the policy?

**Comment by xavierclements** [comment]
OK. I'll adjust the PR - it's just a preference thing where I don't like seeing failed deletes in a stack - particularly if nested.

**Comment by xavierclements** [comment]
> I wish people read the docs haha We had the same issue with DynamoDB tables (using `Retain`) and despite mentioning it in the docs people raised issues in GitHub about their stacks failing because resources already exist.
> 
> But as I mentioned, CloudFormation would not delete a bucket with data anyways, so what is the benefit of the policy?

@jaidisido 784ef6e

**Pull request merged**
