### PR TITLE
Deteleting accidentally added Image files and fixing minor errores in Readme

### PR DESCRIPTION
**Pull request by cantoraa**
*Issue #, if available:*

*Description of changes:*

I have deleted image files that I accidentally added to the Image folder in the first PR. I have also deleted some parameters in the README that are no longer needed because of a better integration with the SDLF (parameter store). I am not sure why it shows too many changes, I did not touch anything else.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaidisido** [comment]
That is strange indeed. The only reason I can think of is that the directory permissions might have changed. When running `ls -lha` in the repository, the `sdlf-utils` directory permissions are `drwxr-xr-x`. Is that similar for yours as well?

**Comment by cantoraa** [comment]
I got the same permissions in the folders and -rw-r--r-- for the specific files.

**Comment by jaidisido** [comment]
Within your own fork of the repository, could you please try to create a PR between your master branch and a branch that holds these changes? This way we can check what the changes were at least

**Comment by cantoraa** [comment]
Let me close this PR and make sure that only what's changed get into a new PR. Thanks!

**Pull request closed without merging**
