### PR TITLE
Added some images which helps in visualizing ASL files

### PR DESCRIPTION
**Pull request by Rstar1998**
*Description of changes:*

- Added file data-quality-asl-visualization.PNG which is a visual representation of data-quality.asl.json file
- Added file stage-a-asl-visualization.PNG which is a visual representation of stage-a.asl.json file
- Added file stage-b-asl-visualization.PNG which is a visual representation of stage-b.asl.json file

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mousamm** [comment]
Hi @Rstar1998 ,

The idea of not having static png files for the state machines is that, these state machines would evolve over a period of time. Hence adding a static image would lead to maintenance overhead. The graph can be easily rendered from asl.json file using any modern IDE and this ensures that the graph is up to date with the definition.

Is there any particular reason as to why you wanted to add these static files?\

Thanks,
Mousam

**Comment by Rstar1998** [comment]
Hi @mousamm .I wanted to include these images because it helps in quickly understanding those state machine pipelines rather than going through the json files. But I agree with your opinion that for any change in asl files we need to change these files.

**Comment by mousamm** [comment]
Thank you, I will close this PR as this can be quickly visualised using any IDE from the asl files itself.

Thanks,
Mousam

**Review by mousamm — COMMENTED** [review]
These images can be generated using any modern IDE from the asl.json files.

**Pull request closed without merging**
